version: "3"

volumes:
  config:
    external: true
  cacheData:
    external: true
  dbData:
    external: true
  influxdbData:
    external: true

services:
  cache:
    restart: unless-stopped
    image: redis:7.0.7-alpine
    command: redis-server --loglevel warning
    volumes:
      - cacheData:/data
    container_name: Cache

  postgres:
      restart: unless-stopped
      image: postgres:15.2-alpine
      environment:
        - POSTGRES_USER=disstat
        - POSTGRES_PASSWORD=AQwrMb4WzngykR9v
        - POSTGRES_DB=disstat
      ports:
        - 5436:5432
      volumes:
        - ./schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
        - dbData:/var/lib/postgresql/data
      container_name: DB

  site:
    restart: unless-stopped
    build: ./siteSrc
    container_name: site
    ports:
      - 80:80
    volumes:
      - config:/config
    depends_on:
      - postgres
      - cache
  
  swagger:
    image: swaggerapi/swagger-ui
    environment:
    - BASE_URL=/docs
    - API_URL=/api/docs/json
    container_name: swagger

  influxdb:
    image: influxdb:2.7.1-alpine
    ports:
      - '8086:8086'
    container_name: influxdb
    volumes:
      - influxdbData:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=disstat
      - DOCKER_INFLUXDB_INIT_BUCKET=defaultBucket
      - DOCKER_INFLUXDB_INIT_USERNAME=disStatAdmin
      - 'DOCKER_INFLUXDB_INIT_PASSWORD=6#Le0zTjR0Q2'
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=yh3dMn8sXX09umUdz!ykW3m&d2PN9s
