name: ESLint

on:
  push:
  pull_request:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    if: github.actor == 'DEVTomatoCake'
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3

      - name: "⏬ install packages"
        run: npm i --omit=optional --include=dev --no-fund --progress=false

      - name: "🔍 lint code"
        run: npx eslint .
