name: ESLint

on:
  push:
    authors:
      - "DEVTomatoCake"
  pull_request:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3

      - name: "🔍 lint code"
        run: npx eslint . --report-unused-disable-directives
